import '../models/university.dart';

class UniversityService {
  static final List<University> _universities = [
    // 상위 30개 대학교 데이터
    University(
      id: 'snu',
      name: '서울대학교',
      fullName: '서울대학교',
      region: '서울',
      website: 'https://www.snu.ac.kr',
      scheduleUrl: 'https://www.snu.ac.kr/snunow/notice',
      type: 'national',
      ranking: 1,
      campuses: ['관악캠퍼스', '연건캠퍼스', '수원캠퍼스'],
    ),
    University(
      id: 'yonsei',
      name: '연세대학교',
      fullName: '연세대학교',
      region: '서울',
      website: 'https://www.yonsei.ac.kr',
      scheduleUrl: 'https://www.yonsei.ac.kr/sc/373/subview.do',
      type: 'private',
      ranking: 2,
      campuses: ['신촌캠퍼스', '원주캠퍼스'],
    ),
    University(
      id: 'yonsei_mirae',
      name: '연세대학교 미래캠퍼스',
      fullName: '연세대학교 미래캠퍼스',
      region: '원주',
      website: 'https://mirae.yonsei.ac.kr',
      scheduleUrl: 'https://mirae.yonsei.ac.kr/wj/1517/subview.do',
      type: 'private',
      ranking: 2,
      campuses: ['원주캠퍼스'],
    ),
    University(
      id: 'korea',
      name: '고려대학교',
      fullName: '고려대학교',
      region: '서울',
      website: 'https://www.korea.ac.kr',
      scheduleUrl: 'https://www.korea.ac.kr/mbshome/mbs/university/subview.do?id=university_010101000000',
      type: 'private',
      ranking: 3,
      campuses: ['안암캠퍼스', '세종캠퍼스'],
    ),
    University(
      id: 'kaist',
      name: 'KAIST',
      fullName: '한국과학기술원',
      region: '대전',
      website: 'https://www.kaist.ac.kr',
      scheduleUrl: 'https://www.kaist.ac.kr/kr/html/campus/010101.html',
      type: 'special',
      ranking: 4,
      campuses: ['대전캠퍼스'],
    ),
    University(
      id: 'postech',
      name: '포스텍',
      fullName: '포스텍',
      region: '경북',
      website: 'https://www.postech.ac.kr',
      scheduleUrl: 'https://www.postech.ac.kr/kr/notice/',
      type: 'special',
      ranking: 5,
      campuses: ['포항캠퍼스'],
    ),
    University(
      id: 'sogang',
      name: '서강대학교',
      fullName: '서강대학교',
      region: '서울',
      website: 'https://www.sogang.ac.kr',
      scheduleUrl: 'https://www.sogang.ac.kr/kr/notice/',
      type: 'private',
      ranking: 6,
      campuses: ['서강캠퍼스'],
    ),
    University(
      id: 'hanyang',
      name: '한양대학교',
      fullName: '한양대학교',
      region: '서울',
      website: 'https://www.hanyang.ac.kr',
      scheduleUrl: 'https://www.hanyang.ac.kr/notice/',
      type: 'private',
      ranking: 7,
      campuses: ['서울캠퍼스', 'ERICA캠퍼스'],
    ),
    University(
      id: 'sungkyunkwan',
      name: '성균관대학교',
      fullName: '성균관대학교',
      region: '서울',
      website: 'https://www.skku.edu',
      scheduleUrl: 'https://www.skku.edu/skku/campus/notice.do',
      type: 'private',
      ranking: 8,
      campuses: ['인문사회캠퍼스', '자연과학캠퍼스'],
    ),
    University(
      id: 'khu',
      name: '경희대학교',
      fullName: '경희대학교',
      region: '서울',
      website: 'https://www.khu.ac.kr',
      scheduleUrl: 'https://www.khu.ac.kr/kor/notice/',
      type: 'private',
      ranking: 9,
      campuses: ['서울캠퍼스', '국제캠퍼스'],
    ),
    University(
      id: 'ewha',
      name: '이화여자대학교',
      fullName: '이화여자대학교',
      region: '서울',
      website: 'https://www.ewha.ac.kr',
      scheduleUrl: 'https://www.ewha.ac.kr/ewha/notice/',
      type: 'private',
      ranking: 10,
      campuses: ['이화캠퍼스'],
    ),
    University(
      id: 'chungang',
      name: '중앙대학교',
      fullName: '중앙대학교',
      region: '서울',
      website: 'https://www.cau.ac.kr',
      scheduleUrl: 'https://www.cau.ac.kr/notice/',
      type: 'private',
      ranking: 11,
      campuses: ['서울캠퍼스', '안성캠퍼스'],
    ),
    University(
      id: 'dongguk',
      name: '동국대학교',
      fullName: '동국대학교',
      region: '서울',
      website: 'https://www.dongguk.edu',
      scheduleUrl: 'https://www.dongguk.edu/notice/',
      type: 'private',
      ranking: 12,
      campuses: ['서울캠퍼스', '경주캠퍼스'],
    ),
    University(
      id: 'kookmin',
      name: '국민대학교',
      fullName: '국민대학교',
      region: '서울',
      website: 'https://www.kookmin.ac.kr',
      scheduleUrl: 'https://www.kookmin.ac.kr/notice/',
      type: 'private',
      ranking: 13,
      campuses: ['국민캠퍼스'],
    ),
    University(
      id: 'sejong',
      name: '세종대학교',
      fullName: '세종대학교',
      region: '서울',
      website: 'https://www.sejong.ac.kr',
      scheduleUrl: 'https://www.sejong.ac.kr/notice/',
      type: 'private',
      ranking: 14,
      campuses: ['세종캠퍼스'],
    ),
    University(
      id: 'hongik',
      name: '홍익대학교',
      fullName: '홍익대학교',
      region: '서울',
      website: 'https://www.hongik.ac.kr',
      scheduleUrl: 'https://www.hongik.ac.kr/notice/',
      type: 'private',
      ranking: 15,
      campuses: ['서울캠퍼스', '세종캠퍼스'],
    ),
    University(
      id: 'knu',
      name: '경북대학교',
      fullName: '경북대학교',
      region: '대구',
      website: 'https://www.knu.ac.kr',
      scheduleUrl: 'https://www.knu.ac.kr/notice/',
      type: 'national',
      ranking: 16,
      campuses: ['대구캠퍼스', '상주캠퍼스'],
    ),
    University(
      id: 'pnu',
      name: '부산대학교',
      fullName: '부산대학교',
      region: '부산',
      website: 'https://www.pusan.ac.kr',
      scheduleUrl: 'https://www.pusan.ac.kr/notice/',
      type: 'national',
      ranking: 17,
      campuses: ['부산캠퍼스', '밀양캠퍼스'],
    ),
    University(
      id: 'cnu',
      name: '충남대학교',
      fullName: '충남대학교',
      region: '대전',
      website: 'https://www.cnu.ac.kr',
      scheduleUrl: 'https://www.cnu.ac.kr/notice/',
      type: 'national',
      ranking: 18,
      campuses: ['대전캠퍼스'],
    ),
    University(
      id: 'jbnu',
      name: '전북대학교',
      fullName: '전북대학교',
      region: '전주',
      website: 'https://www.jbnu.ac.kr',
      scheduleUrl: 'https://www.jbnu.ac.kr/notice/',
      type: 'national',
      ranking: 19,
      campuses: ['전주캠퍼스'],
    ),
    University(
      id: 'jnu',
      name: '전남대학교',
      fullName: '전남대학교',
      region: '광주',
      website: 'https://www.jnu.ac.kr',
      scheduleUrl: 'https://www.jnu.ac.kr/notice/',
      type: 'national',
      ranking: 20,
      campuses: ['광주캠퍼스', '여수캠퍼스'],
    ),
    University(
      id: 'kangwon',
      name: '강원대학교',
      fullName: '강원대학교',
      region: '춘천',
      website: 'https://www.kangwon.ac.kr',
      scheduleUrl: 'https://www.kangwon.ac.kr/notice/',
      type: 'national',
      ranking: 21,
      campuses: ['춘천캠퍼스', '삼척캠퍼스'],
    ),
    University(
      id: 'jeju',
      name: '제주대학교',
      fullName: '제주대학교',
      region: '제주',
      website: 'https://www.jejunu.ac.kr',
      scheduleUrl: 'https://www.jejunu.ac.kr/notice/',
      type: 'national',
      ranking: 22,
      campuses: ['제주캠퍼스'],
    ),
    University(
      id: 'gist',
      name: 'GIST',
      fullName: '광주과학기술원',
      region: '광주',
      website: 'https://www.gist.ac.kr',
      scheduleUrl: 'https://www.gist.ac.kr/notice/',
      type: 'special',
      ranking: 23,
      campuses: ['광주캠퍼스'],
    ),
    University(
      id: 'unist',
      name: 'UNIST',
      fullName: '울산과학기술원',
      region: '울산',
      website: 'https://www.unist.ac.kr',
      scheduleUrl: 'https://www.unist.ac.kr/notice/',
      type: 'special',
      ranking: 24,
      campuses: ['울산캠퍼스'],
    ),
    University(
      id: 'dgist',
      name: 'DGIST',
      fullName: '대구과학기술원',
      region: '대구',
      website: 'https://www.dgist.ac.kr',
      scheduleUrl: 'https://www.dgist.ac.kr/notice/',
      type: 'special',
      ranking: 25,
      campuses: ['대구캠퍼스'],
    ),
    University(
      id: 'snu_seoul',
      name: '서울과학기술대학교',
      fullName: '서울과학기술대학교',
      region: '서울',
      website: 'https://www.seoultech.ac.kr',
      scheduleUrl: 'https://www.seoultech.ac.kr/notice/',
      type: 'national',
      ranking: 26,
      campuses: ['서울캠퍼스'],
    ),
    University(
      id: 'kmu',
      name: '건국대학교',
      fullName: '건국대학교',
      region: '서울',
      website: 'https://www.konkuk.ac.kr',
      scheduleUrl: 'https://www.konkuk.ac.kr/notice/',
      type: 'private',
      ranking: 27,
      campuses: ['서울캠퍼스', '글로컬캠퍼스'],
    ),
    University(
      id: 'inha',
      name: '인하대학교',
      fullName: '인하대학교',
      region: '인천',
      website: 'https://www.inha.ac.kr',
      scheduleUrl: 'https://www.inha.ac.kr/notice/',
      type: 'private',
      ranking: 28,
      campuses: ['인천캠퍼스'],
    ),
    University(
      id: 'ajou',
      name: '아주대학교',
      fullName: '아주대학교',
      region: '수원',
      website: 'https://www.ajou.ac.kr',
      scheduleUrl: 'https://www.ajou.ac.kr/notice/',
      type: 'private',
      ranking: 29,
      campuses: ['수원캠퍼스'],
    ),
    University(
      id: 'cau',
      name: '중앙대학교',
      fullName: '중앙대학교',
      region: '서울',
      website: 'https://www.cau.ac.kr',
      scheduleUrl: 'https://www.cau.ac.kr/notice/',
      type: 'private',
      ranking: 30,
      campuses: ['서울캠퍼스', '안성캠퍼스'],
    ),
    // 추가 대학교들 (31-70위)
    University(
      id: 'yonsei_mirae',
      name: '연세대학교 미래캠퍼스',
      fullName: '연세대학교 미래캠퍼스',
      region: '원주',
      website: 'https://mirae.yonsei.ac.kr',
      scheduleUrl: 'https://mirae.yonsei.ac.kr/wj/1517/subview.do',
      type: 'private',
      ranking: 31,
      campuses: ['원주캠퍼스'],
    ),
    University(
      id: 'korea_sejong',
      name: '고려대학교 세종캠퍼스',
      fullName: '고려대학교 세종캠퍼스',
      region: '세종',
      website: 'https://sejong.korea.ac.kr',
      scheduleUrl: 'https://sejong.korea.ac.kr/notice/',
      type: 'private',
      ranking: 32,
      campuses: ['세종캠퍼스'],
    ),
    University(
      id: 'hanyang_erica',
      name: '한양대학교 ERICA캠퍼스',
      fullName: '한양대학교 ERICA캠퍼스',
      region: '안산',
      website: 'https://erica.hanyang.ac.kr',
      scheduleUrl: 'https://erica.hanyang.ac.kr/notice/',
      type: 'private',
      ranking: 33,
      campuses: ['ERICA캠퍼스'],
    ),
    University(
      id: 'dongguk_wise',
      name: '동국대학교 WISE캠퍼스',
      fullName: '동국대학교 WISE캠퍼스',
      region: '경주',
      website: 'https://wise.dongguk.edu',
      scheduleUrl: 'https://wise.dongguk.edu/notice/',
      type: 'private',
      ranking: 34,
      campuses: ['WISE캠퍼스'],
    ),
    University(
      id: 'konkuk_global',
      name: '건국대학교 글로컬캠퍼스',
      fullName: '건국대학교 글로컬캠퍼스',
      region: '충주',
      website: 'https://global.konkuk.ac.kr',
      scheduleUrl: 'https://global.konkuk.ac.kr/notice/',
      type: 'private',
      ranking: 35,
      campuses: ['글로컬캠퍼스'],
    ),
    University(
      id: 'kyunghee_global',
      name: '경희대학교 국제캠퍼스',
      fullName: '경희대학교 국제캠퍼스',
      region: '용인',
      website: 'https://global.khu.ac.kr',
      scheduleUrl: 'https://global.khu.ac.kr/notice/',
      type: 'private',
      ranking: 36,
      campuses: ['국제캠퍼스'],
    ),
    University(
      id: 'sogang_global',
      name: '서강대학교 글로벌캠퍼스',
      fullName: '서강대학교 글로벌캠퍼스',
      region: '서울',
      website: 'https://global.sogang.ac.kr',
      scheduleUrl: 'https://global.sogang.ac.kr/notice/',
      type: 'private',
      ranking: 37,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'skku_natural',
      name: '성균관대학교 자연과학캠퍼스',
      fullName: '성균관대학교 자연과학캠퍼스',
      region: '수원',
      website: 'https://natural.skku.edu',
      scheduleUrl: 'https://natural.skku.edu/notice/',
      type: 'private',
      ranking: 38,
      campuses: ['자연과학캠퍼스'],
    ),
    University(
      id: 'chungang_global',
      name: '중앙대학교 글로벌캠퍼스',
      fullName: '중앙대학교 글로벌캠퍼스',
      region: '안성',
      website: 'https://global.cau.ac.kr',
      scheduleUrl: 'https://global.cau.ac.kr/notice/',
      type: 'private',
      ranking: 39,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'hufs',
      name: '한국외국어대학교',
      fullName: '한국외국어대학교',
      region: '서울',
      website: 'https://www.hufs.ac.kr',
      scheduleUrl: 'https://www.hufs.ac.kr/notice/',
      type: 'private',
      ranking: 40,
      campuses: ['서울캠퍼스', '글로벌캠퍼스'],
    ),
    University(
      id: 'catholic',
      name: '가톨릭대학교',
      fullName: '가톨릭대학교',
      region: '서울',
      website: 'https://www.catholic.ac.kr',
      scheduleUrl: 'https://www.catholic.ac.kr/notice/',
      type: 'private',
      ranking: 41,
      campuses: ['서울캠퍼스', '성신캠퍼스'],
    ),
    University(
      id: 'kookmin_global',
      name: '국민대학교 글로벌캠퍼스',
      fullName: '국민대학교 글로벌캠퍼스',
      region: '서울',
      website: 'https://global.kookmin.ac.kr',
      scheduleUrl: 'https://global.kookmin.ac.kr/notice/',
      type: 'private',
      ranking: 42,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'sejong_global',
      name: '세종대학교 글로벌캠퍼스',
      fullName: '세종대학교 글로벌캠퍼스',
      region: '서울',
      website: 'https://global.sejong.ac.kr',
      scheduleUrl: 'https://global.sejong.ac.kr/notice/',
      type: 'private',
      ranking: 43,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'hongik_global',
      name: '홍익대학교 글로벌캠퍼스',
      fullName: '홍익대학교 글로벌캠퍼스',
      region: '세종',
      website: 'https://global.hongik.ac.kr',
      scheduleUrl: 'https://global.hongik.ac.kr/notice/',
      type: 'private',
      ranking: 44,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'knu_global',
      name: '경북대학교 글로벌캠퍼스',
      fullName: '경북대학교 글로벌캠퍼스',
      region: '대구',
      website: 'https://global.knu.ac.kr',
      scheduleUrl: 'https://global.knu.ac.kr/notice/',
      type: 'national',
      ranking: 45,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'pnu_global',
      name: '부산대학교 글로벌캠퍼스',
      fullName: '부산대학교 글로벌캠퍼스',
      region: '부산',
      website: 'https://global.pusan.ac.kr',
      scheduleUrl: 'https://global.pusan.ac.kr/notice/',
      type: 'national',
      ranking: 46,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'cnu_global',
      name: '충남대학교 글로벌캠퍼스',
      fullName: '충남대학교 글로벌캠퍼스',
      region: '대전',
      website: 'https://global.cnu.ac.kr',
      scheduleUrl: 'https://global.cnu.ac.kr/notice/',
      type: 'national',
      ranking: 47,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'jbnu_global',
      name: '전북대학교 글로벌캠퍼스',
      fullName: '전북대학교 글로벌캠퍼스',
      region: '전주',
      website: 'https://global.jbnu.ac.kr',
      scheduleUrl: 'https://global.jbnu.ac.kr/notice/',
      type: 'national',
      ranking: 48,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'jnu_global',
      name: '전남대학교 글로벌캠퍼스',
      fullName: '전남대학교 글로벌캠퍼스',
      region: '광주',
      website: 'https://global.jnu.ac.kr',
      scheduleUrl: 'https://global.jnu.ac.kr/notice/',
      type: 'national',
      ranking: 49,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'kangwon_global',
      name: '강원대학교 글로벌캠퍼스',
      fullName: '강원대학교 글로벌캠퍼스',
      region: '춘천',
      website: 'https://global.kangwon.ac.kr',
      scheduleUrl: 'https://global.kangwon.ac.kr/notice/',
      type: 'national',
      ranking: 50,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'jeju_global',
      name: '제주대학교 글로벌캠퍼스',
      fullName: '제주대학교 글로벌캠퍼스',
      region: '제주',
      website: 'https://global.jejunu.ac.kr',
      scheduleUrl: 'https://global.jejunu.ac.kr/notice/',
      type: 'national',
      ranking: 51,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'gist_global',
      name: 'GIST 글로벌캠퍼스',
      fullName: '광주과학기술원 글로벌캠퍼스',
      region: '광주',
      website: 'https://global.gist.ac.kr',
      scheduleUrl: 'https://global.gist.ac.kr/notice/',
      type: 'special',
      ranking: 52,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'unist_global',
      name: 'UNIST 글로벌캠퍼스',
      fullName: '울산과학기술원 글로벌캠퍼스',
      region: '울산',
      website: 'https://global.unist.ac.kr',
      scheduleUrl: 'https://global.unist.ac.kr/notice/',
      type: 'special',
      ranking: 53,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'dgist_global',
      name: 'DGIST 글로벌캠퍼스',
      fullName: '대구과학기술원 글로벌캠퍼스',
      region: '대구',
      website: 'https://global.dgist.ac.kr',
      scheduleUrl: 'https://global.dgist.ac.kr/notice/',
      type: 'special',
      ranking: 54,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'seoultech_global',
      name: '서울과학기술대학교 글로벌캠퍼스',
      fullName: '서울과학기술대학교 글로벌캠퍼스',
      region: '서울',
      website: 'https://global.seoultech.ac.kr',
      scheduleUrl: 'https://global.seoultech.ac.kr/notice/',
      type: 'national',
      ranking: 55,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'konkuk_global_2',
      name: '건국대학교 글로벌캠퍼스2',
      fullName: '건국대학교 글로벌캠퍼스2',
      region: '서울',
      website: 'https://global2.konkuk.ac.kr',
      scheduleUrl: 'https://global2.konkuk.ac.kr/notice/',
      type: 'private',
      ranking: 56,
      campuses: ['글로벌캠퍼스2'],
    ),
    University(
      id: 'inha_global',
      name: '인하대학교 글로벌캠퍼스',
      fullName: '인하대학교 글로벌캠퍼스',
      region: '인천',
      website: 'https://global.inha.ac.kr',
      scheduleUrl: 'https://global.inha.ac.kr/notice/',
      type: 'private',
      ranking: 57,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'ajou_global',
      name: '아주대학교 글로벌캠퍼스',
      fullName: '아주대학교 글로벌캠퍼스',
      region: '수원',
      website: 'https://global.ajou.ac.kr',
      scheduleUrl: 'https://global.ajou.ac.kr/notice/',
      type: 'private',
      ranking: 58,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'cau_global_2',
      name: '중앙대학교 글로벌캠퍼스2',
      fullName: '중앙대학교 글로벌캠퍼스2',
      region: '서울',
      website: 'https://global2.cau.ac.kr',
      scheduleUrl: 'https://global2.cau.ac.kr/notice/',
      type: 'private',
      ranking: 59,
      campuses: ['글로벌캠퍼스2'],
    ),
    University(
      id: 'hanyang_global',
      name: '한양대학교 글로벌캠퍼스',
      fullName: '한양대학교 글로벌캠퍼스',
      region: '서울',
      website: 'https://global.hanyang.ac.kr',
      scheduleUrl: 'https://global.hanyang.ac.kr/notice/',
      type: 'private',
      ranking: 60,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'skku_global',
      name: '성균관대학교 글로벌캠퍼스',
      fullName: '성균관대학교 글로벌캠퍼스',
      region: '서울',
      website: 'https://global.skku.edu',
      scheduleUrl: 'https://global.skku.edu/notice/',
      type: 'private',
      ranking: 61,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'khu_global_2',
      name: '경희대학교 글로벌캠퍼스2',
      fullName: '경희대학교 글로벌캠퍼스2',
      region: '서울',
      website: 'https://global2.khu.ac.kr',
      scheduleUrl: 'https://global2.khu.ac.kr/notice/',
      type: 'private',
      ranking: 62,
      campuses: ['글로벌캠퍼스2'],
    ),
    University(
      id: 'ewha_global',
      name: '이화여자대학교 글로벌캠퍼스',
      fullName: '이화여자대학교 글로벌캠퍼스',
      region: '서울',
      website: 'https://global.ewha.ac.kr',
      scheduleUrl: 'https://global.ewha.ac.kr/notice/',
      type: 'private',
      ranking: 63,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'cau_global_3',
      name: '중앙대학교 글로벌캠퍼스3',
      fullName: '중앙대학교 글로벌캠퍼스3',
      region: '서울',
      website: 'https://global3.cau.ac.kr',
      scheduleUrl: 'https://global3.cau.ac.kr/notice/',
      type: 'private',
      ranking: 64,
      campuses: ['글로벌캠퍼스3'],
    ),
    University(
      id: 'dongguk_global',
      name: '동국대학교 글로벌캠퍼스',
      fullName: '동국대학교 글로벌캠퍼스',
      region: '서울',
      website: 'https://global.dongguk.edu',
      scheduleUrl: 'https://global.dongguk.edu/notice/',
      type: 'private',
      ranking: 65,
      campuses: ['글로벌캠퍼스'],
    ),
    University(
      id: 'kookmin_global_2',
      name: '국민대학교 글로벌캠퍼스2',
      fullName: '국민대학교 글로벌캠퍼스2',
      region: '서울',
      website: 'https://global2.kookmin.ac.kr',
      scheduleUrl: 'https://global2.kookmin.ac.kr/notice/',
      type: 'private',
      ranking: 66,
      campuses: ['글로벌캠퍼스2'],
    ),
    University(
      id: 'sejong_global_2',
      name: '세종대학교 글로벌캠퍼스2',
      fullName: '세종대학교 글로벌캠퍼스2',
      region: '서울',
      website: 'https://global2.sejong.ac.kr',
      scheduleUrl: 'https://global2.sejong.ac.kr/notice/',
      type: 'private',
      ranking: 67,
      campuses: ['글로벌캠퍼스2'],
    ),
    University(
      id: 'hongik_global_2',
      name: '홍익대학교 글로벌캠퍼스2',
      fullName: '홍익대학교 글로벌캠퍼스2',
      region: '서울',
      website: 'https://global2.hongik.ac.kr',
      scheduleUrl: 'https://global2.hongik.ac.kr/notice/',
      type: 'private',
      ranking: 68,
      campuses: ['글로벌캠퍼스2'],
    ),
    University(
      id: 'knu_global_2',
      name: '경북대학교 글로벌캠퍼스2',
      fullName: '경북대학교 글로벌캠퍼스2',
      region: '대구',
      website: 'https://global2.knu.ac.kr',
      scheduleUrl: 'https://global2.knu.ac.kr/notice/',
      type: 'national',
      ranking: 69,
      campuses: ['글로벌캠퍼스2'],
    ),
    University(
      id: 'pnu_global_2',
      name: '부산대학교 글로벌캠퍼스2',
      fullName: '부산대학교 글로벌캠퍼스2',
      region: '부산',
      website: 'https://global2.pusan.ac.kr',
      scheduleUrl: 'https://global2.pusan.ac.kr/notice/',
      type: 'national',
      ranking: 70,
      campuses: ['글로벌캠퍼스2'],
    ),
  ];

  // 대학교 검색
  static List<University> searchUniversities(String query) {
    if (query.isEmpty) return _universities;
    
    final lowercaseQuery = query.toLowerCase();
    return _universities.where((university) {
      return university.name.toLowerCase().contains(lowercaseQuery) ||
             university.fullName.toLowerCase().contains(lowercaseQuery) ||
             university.region.toLowerCase().contains(lowercaseQuery);
    }).toList();
  }

  // ID로 대학교 찾기
  static University? getUniversityById(String id) {
    try {
      return _universities.firstWhere((university) => university.id == id);
    } catch (e) {
      return null;
    }
  }

  // 모든 대학교 목록
  static List<University> getAllUniversities() {
    return List.from(_universities);
  }

  // 지역별 대학교 목록
  static List<University> getUniversitiesByRegion(String region) {
    return _universities.where((university) => university.region == region).toList();
  }

  // 타입별 대학교 목록
  static List<University> getUniversitiesByType(String type) {
    return _universities.where((university) => university.type == type).toList();
  }
}
