steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/learnus-backend', '.']
  
  # Docker 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/learnus-backend']
  
  # Cloud Run에 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'learnus-backend',
      '--image', 'gcr.io/$PROJECT_ID/learnus-backend',
      '--platform', 'managed',
      '--region', 'asia-northeast3',
      '--allow-unauthenticated',
      '--memory', '2Gi',
      '--cpu', '2',
      '--timeout', '3600',
      '--max-instances', '10',
      '--min-instances', '0'
    ]

# 로깅 설정 추가
options:
  logging: CLOUD_LOGGING_ONLY
